/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToojouRentRouteImport } from './routes/toojou-rent'
import { Route as PaikesepargidRouteImport } from './routes/paikesepargid'
import { Route as PaikesepaneelidRouteImport } from './routes/paikesepaneelid'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TehtudToodIndexRouteImport } from './routes/tehtud-tood/index'
import { Route as BlogiIndexRouteImport } from './routes/blogi/index'
import { Route as TehtudToodSlugRouteImport } from './routes/tehtud-tood/$slug'
import { Route as BlogiSlugRouteImport } from './routes/blogi/$slug'

const ToojouRentRoute = ToojouRentRouteImport.update({
  id: '/toojou-rent',
  path: '/toojou-rent',
  getParentRoute: () => rootRouteImport,
} as any)
const PaikesepargidRoute = PaikesepargidRouteImport.update({
  id: '/paikesepargid',
  path: '/paikesepargid',
  getParentRoute: () => rootRouteImport,
} as any)
const PaikesepaneelidRoute = PaikesepaneelidRouteImport.update({
  id: '/paikesepaneelid',
  path: '/paikesepaneelid',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TehtudToodIndexRoute = TehtudToodIndexRouteImport.update({
  id: '/tehtud-tood/',
  path: '/tehtud-tood/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogiIndexRoute = BlogiIndexRouteImport.update({
  id: '/blogi/',
  path: '/blogi/',
  getParentRoute: () => rootRouteImport,
} as any)
const TehtudToodSlugRoute = TehtudToodSlugRouteImport.update({
  id: '/tehtud-tood/$slug',
  path: '/tehtud-tood/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogiSlugRoute = BlogiSlugRouteImport.update({
  id: '/blogi/$slug',
  path: '/blogi/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/paikesepaneelid': typeof PaikesepaneelidRoute
  '/paikesepargid': typeof PaikesepargidRoute
  '/toojou-rent': typeof ToojouRentRoute
  '/blogi/$slug': typeof BlogiSlugRoute
  '/tehtud-tood/$slug': typeof TehtudToodSlugRoute
  '/blogi/': typeof BlogiIndexRoute
  '/tehtud-tood/': typeof TehtudToodIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/paikesepaneelid': typeof PaikesepaneelidRoute
  '/paikesepargid': typeof PaikesepargidRoute
  '/toojou-rent': typeof ToojouRentRoute
  '/blogi/$slug': typeof BlogiSlugRoute
  '/tehtud-tood/$slug': typeof TehtudToodSlugRoute
  '/blogi': typeof BlogiIndexRoute
  '/tehtud-tood': typeof TehtudToodIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/paikesepaneelid': typeof PaikesepaneelidRoute
  '/paikesepargid': typeof PaikesepargidRoute
  '/toojou-rent': typeof ToojouRentRoute
  '/blogi/$slug': typeof BlogiSlugRoute
  '/tehtud-tood/$slug': typeof TehtudToodSlugRoute
  '/blogi/': typeof BlogiIndexRoute
  '/tehtud-tood/': typeof TehtudToodIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kontakt'
    | '/paikesepaneelid'
    | '/paikesepargid'
    | '/toojou-rent'
    | '/blogi/$slug'
    | '/tehtud-tood/$slug'
    | '/blogi/'
    | '/tehtud-tood/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kontakt'
    | '/paikesepaneelid'
    | '/paikesepargid'
    | '/toojou-rent'
    | '/blogi/$slug'
    | '/tehtud-tood/$slug'
    | '/blogi'
    | '/tehtud-tood'
  id:
    | '__root__'
    | '/'
    | '/kontakt'
    | '/paikesepaneelid'
    | '/paikesepargid'
    | '/toojou-rent'
    | '/blogi/$slug'
    | '/tehtud-tood/$slug'
    | '/blogi/'
    | '/tehtud-tood/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktRoute: typeof KontaktRoute
  PaikesepaneelidRoute: typeof PaikesepaneelidRoute
  PaikesepargidRoute: typeof PaikesepargidRoute
  ToojouRentRoute: typeof ToojouRentRoute
  BlogiSlugRoute: typeof BlogiSlugRoute
  TehtudToodSlugRoute: typeof TehtudToodSlugRoute
  BlogiIndexRoute: typeof BlogiIndexRoute
  TehtudToodIndexRoute: typeof TehtudToodIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/toojou-rent': {
      id: '/toojou-rent'
      path: '/toojou-rent'
      fullPath: '/toojou-rent'
      preLoaderRoute: typeof ToojouRentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paikesepargid': {
      id: '/paikesepargid'
      path: '/paikesepargid'
      fullPath: '/paikesepargid'
      preLoaderRoute: typeof PaikesepargidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paikesepaneelid': {
      id: '/paikesepaneelid'
      path: '/paikesepaneelid'
      fullPath: '/paikesepaneelid'
      preLoaderRoute: typeof PaikesepaneelidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tehtud-tood/': {
      id: '/tehtud-tood/'
      path: '/tehtud-tood'
      fullPath: '/tehtud-tood/'
      preLoaderRoute: typeof TehtudToodIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogi/': {
      id: '/blogi/'
      path: '/blogi'
      fullPath: '/blogi/'
      preLoaderRoute: typeof BlogiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tehtud-tood/$slug': {
      id: '/tehtud-tood/$slug'
      path: '/tehtud-tood/$slug'
      fullPath: '/tehtud-tood/$slug'
      preLoaderRoute: typeof TehtudToodSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogi/$slug': {
      id: '/blogi/$slug'
      path: '/blogi/$slug'
      fullPath: '/blogi/$slug'
      preLoaderRoute: typeof BlogiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktRoute: KontaktRoute,
  PaikesepaneelidRoute: PaikesepaneelidRoute,
  PaikesepargidRoute: PaikesepargidRoute,
  ToojouRentRoute: ToojouRentRoute,
  BlogiSlugRoute: BlogiSlugRoute,
  TehtudToodSlugRoute: TehtudToodSlugRoute,
  BlogiIndexRoute: BlogiIndexRoute,
  TehtudToodIndexRoute: TehtudToodIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
