/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToojouRentRouteImport } from './routes/toojou-rent'
import { Route as PaikesepargidRouteImport } from './routes/paikesepargid'
import { Route as PaikesepaneelidRouteImport } from './routes/paikesepaneelid'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TehtudToodIndexRouteImport } from './routes/tehtud-tood/index'
import { Route as BlogiIndexRouteImport } from './routes/blogi/index'
import { Route as TehtudToodSlugRouteImport } from './routes/tehtud-tood/$slug'
import { Route as BlogiSlugRouteImport } from './routes/blogi/$slug'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const ToojouRentRoute = ToojouRentRouteImport.update({
  id: '/toojou-rent',
  path: '/toojou-rent',
  getParentRoute: () => rootRouteImport,
} as any)
const PaikesepargidRoute = PaikesepargidRouteImport.update({
  id: '/paikesepargid',
  path: '/paikesepargid',
  getParentRoute: () => rootRouteImport,
} as any)
const PaikesepaneelidRoute = PaikesepaneelidRouteImport.update({
  id: '/paikesepaneelid',
  path: '/paikesepaneelid',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TehtudToodIndexRoute = TehtudToodIndexRouteImport.update({
  id: '/tehtud-tood/',
  path: '/tehtud-tood/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogiIndexRoute = BlogiIndexRouteImport.update({
  id: '/blogi/',
  path: '/blogi/',
  getParentRoute: () => rootRouteImport,
} as any)
const TehtudToodSlugRoute = TehtudToodSlugRouteImport.update({
  id: '/tehtud-tood/$slug',
  path: '/tehtud-tood/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogiSlugRoute = BlogiSlugRouteImport.update({
  id: '/blogi/$slug',
  path: '/blogi/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/mcp': typeof McpRoute
  '/paikesepaneelid': typeof PaikesepaneelidRoute
  '/paikesepargid': typeof PaikesepargidRoute
  '/toojou-rent': typeof ToojouRentRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blogi/$slug': typeof BlogiSlugRoute
  '/tehtud-tood/$slug': typeof TehtudToodSlugRoute
  '/blogi/': typeof BlogiIndexRoute
  '/tehtud-tood/': typeof TehtudToodIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/mcp': typeof McpRoute
  '/paikesepaneelid': typeof PaikesepaneelidRoute
  '/paikesepargid': typeof PaikesepargidRoute
  '/toojou-rent': typeof ToojouRentRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blogi/$slug': typeof BlogiSlugRoute
  '/tehtud-tood/$slug': typeof TehtudToodSlugRoute
  '/blogi': typeof BlogiIndexRoute
  '/tehtud-tood': typeof TehtudToodIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/mcp': typeof McpRoute
  '/paikesepaneelid': typeof PaikesepaneelidRoute
  '/paikesepargid': typeof PaikesepargidRoute
  '/toojou-rent': typeof ToojouRentRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blogi/$slug': typeof BlogiSlugRoute
  '/tehtud-tood/$slug': typeof TehtudToodSlugRoute
  '/blogi/': typeof BlogiIndexRoute
  '/tehtud-tood/': typeof TehtudToodIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kontakt'
    | '/mcp'
    | '/paikesepaneelid'
    | '/paikesepargid'
    | '/toojou-rent'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blogi/$slug'
    | '/tehtud-tood/$slug'
    | '/blogi/'
    | '/tehtud-tood/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kontakt'
    | '/mcp'
    | '/paikesepaneelid'
    | '/paikesepargid'
    | '/toojou-rent'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blogi/$slug'
    | '/tehtud-tood/$slug'
    | '/blogi'
    | '/tehtud-tood'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/kontakt'
    | '/mcp'
    | '/paikesepaneelid'
    | '/paikesepargid'
    | '/toojou-rent'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blogi/$slug'
    | '/tehtud-tood/$slug'
    | '/blogi/'
    | '/tehtud-tood/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktRoute: typeof KontaktRoute
  McpRoute: typeof McpRoute
  PaikesepaneelidRoute: typeof PaikesepaneelidRoute
  PaikesepargidRoute: typeof PaikesepargidRoute
  ToojouRentRoute: typeof ToojouRentRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  BlogiSlugRoute: typeof BlogiSlugRoute
  TehtudToodSlugRoute: typeof TehtudToodSlugRoute
  BlogiIndexRoute: typeof BlogiIndexRoute
  TehtudToodIndexRoute: typeof TehtudToodIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/toojou-rent': {
      id: '/toojou-rent'
      path: '/toojou-rent'
      fullPath: '/toojou-rent'
      preLoaderRoute: typeof ToojouRentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paikesepargid': {
      id: '/paikesepargid'
      path: '/paikesepargid'
      fullPath: '/paikesepargid'
      preLoaderRoute: typeof PaikesepargidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paikesepaneelid': {
      id: '/paikesepaneelid'
      path: '/paikesepaneelid'
      fullPath: '/paikesepaneelid'
      preLoaderRoute: typeof PaikesepaneelidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tehtud-tood/': {
      id: '/tehtud-tood/'
      path: '/tehtud-tood'
      fullPath: '/tehtud-tood/'
      preLoaderRoute: typeof TehtudToodIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogi/': {
      id: '/blogi/'
      path: '/blogi'
      fullPath: '/blogi/'
      preLoaderRoute: typeof BlogiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tehtud-tood/$slug': {
      id: '/tehtud-tood/$slug'
      path: '/tehtud-tood/$slug'
      fullPath: '/tehtud-tood/$slug'
      preLoaderRoute: typeof TehtudToodSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogi/$slug': {
      id: '/blogi/$slug'
      path: '/blogi/$slug'
      fullPath: '/blogi/$slug'
      preLoaderRoute: typeof BlogiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktRoute: KontaktRoute,
  McpRoute: McpRoute,
  PaikesepaneelidRoute: PaikesepaneelidRoute,
  PaikesepargidRoute: PaikesepargidRoute,
  ToojouRentRoute: ToojouRentRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  BlogiSlugRoute: BlogiSlugRoute,
  TehtudToodSlugRoute: TehtudToodSlugRoute,
  BlogiIndexRoute: BlogiIndexRoute,
  TehtudToodIndexRoute: TehtudToodIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
